#!/bin/sh
DIR="$(dirname $0)"
VAGRANT_INVENTORY="$DIR/../.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"

if [ -f $VAGRANT_INVENTORY ]; then
  cat $VAGRANT_INVENTORY 2>/dev/null
else
  echo {}
fi
